config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
      # Redirests signing out users back to sign-in
      get "users", to: "devise/sessions#new"
  end

  get '/users/:id', to: 'users#show', as: 'user'
  

  resources :events
  resources :invitations

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  validates_inclusion_of :date, 
  in: Date.today..Date.today+99.years,
  message: "Must be set in the future"


  scope :past_events, -> {where("created_at <= ?", Date.today)}
  scope :upcoming_events, -> {where("created_at >= ?", Date.today)}

  
  belongs_to :creator, class_name: 'User'
  has_many :invitations, dependent: :destroy
  has_many :attendees, through: :invitations
end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :attendee, class_name: 'User'
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: :creator_id, class_name: 'Event'
  has_many :invitations, foreign_key: 'attendee_id'
  has_many :attended_events, through: :invitations, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController


  def index
    @events = Event.all
  end

  def new
    @event = Event.new
  end

  def show
    @chosen_event = Event.find(params[:id])
    
  end

  def create
    @event = current_user.created_events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to :root, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def event_params
    params.require(:event).permit(:title, :location, :creator_id, :date)
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :set_invitation, only: %i[ show edit update destroy ]

  # GET /invitations or /invitations.json
  def index
    @invitations = Invitation.all
  end

  # GET /invitations/1 or /invitations/1.json
  def show
  end

  # GET /invitations/new
  def new
    @invitation = Invitation.new
  end

  # GET /invitations/1/edit
  def edit
  end

  # POST /invitations or /invitations.json
  def create
    @invitation = current_user.invitations.build(invitation_params)

    respond_to do |format|
      if @invitation.save
        format.html { redirect_to invitation_url(@invitation), notice: "Invitation was successfully created." }
        format.json { render :show, status: :created, location: @invitation }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /invitations/1 or /invitations/1.json
  def update
    respond_to do |format|
      if @invitation.update(invitation_params)
        format.html { redirect_to invitation_url(@invitation), notice: "Invitation was successfully updated." }
        format.json { render :show, status: :ok, location: @invitation }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @invitation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /invitations/1 or /invitations/1.json
  def destroy
    @invitation.destroy

    respond_to do |format|
      format.html { redirect_to root_path, notice: "Invitation was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_invitation
      @invitation = Invitation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def invitation_params
      params.require(:invitation).permit(:event_id, :attendee_id)
    end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        if get?
          raise e
        elsif has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end
  
    self.responder = Responder
    respond_to :html, :turbo_stream
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = current_user
    @organized_events = current_user.created_events.all
    @attended_events = current_user.attended_events.all
    @past_events = Event.all.where("created_at <= ?", Date.today)
    @future_events = Event.all.where("created_at >= ?", Date.today)
    
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/events/_event.html.erb
<br><span><%= event.title %></span>
<span><%= event.location %></span><br>
<%= link_to 'Event Details', event_path(event), method: :get %>
<br>

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.text_area :location %>
  </div>
  <div> 
    <%= form.label :date %> 
    <%= form.date_field :date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/events/index.html.erb
<div class="flex flex-row items-center justify-between h-16 mb-10">
  <div class="flex flex-row">
    <% if user_signed_in? %>
       <br><p><%= current_user.name %></p><br>
    <% else %>
       <br><span>Please Sign In</span><br>
    <% end %>
  </div> 
  
   <div class="flex flex-row  w-1/3">
     <% if user_signed_in? %>
        <%= button_to 'New Event', new_event_path, method: :get, class:'bg-blue-500 font-mono mx-4  w-24 px-1 hover: bg-blue-600 text-white rounded' %>
        <%= button_to 'My Events', user_path(current_user), method: :get, class:'bg-blue-500 mx-4 font-mono w-24 px-1 hover: bg-blue-600 text-white rounded' %>
        <%= button_to 'Logout', destroy_user_session_path, method: :delete, class:'bg-blue-500 mx-4  font-mono w-24 px-1 hover: bg-blue-600 text-white rounded' %>
      <% else %>
        <%= button_to 'Sign In', new_user_session_path, method: :get, class:'bg-blue-500 mx-4   font-mono w-24 px-1hover: bg-blue-600 text-white rounded' %>
        <%= button_to 'Register', new_user_registration_path, method: :get, class:'bg-blue-500 mx-4  w-24 px-1 font-mono hover: bg-blue-600 text-white rounded' %>
       <% end %>
   </div>
</div>

<p class="notice flex flex-row  text-green-500 items-center justify-center w-screen h-2vh"><%= notice %></p>
<p class="alert flex flex-row  text-red-500 items-center justify-center w-screen h-2vh"><%= alert %></p>

<div class="flex flex-row justify-around w-screen ">
  <div class="flex flex-col  items-center mr-12">
    <h1>upcoming events</h1>
    <% @events.upcoming_events.each do |event| %>
      <%= render event%>
    <% end %>
  </div>
  
  <div class="flex flex-col items-center">
    <h1>past events</h1>
    <% @events.past_events.each do |event| %>
      <%= render event%>
    <% end %>
  </div>
</div>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render "form", event: @event %>

<br>

app/views/events/show.html.erb
<%= @chosen_event.title %>
<%= @chosen_event.location %>

<%= @chosen_event.attendees.each do |guest|%>
<br>
  <br>
  <%= guest.name%>
  <br>
  <br>
<% end %>
 <br>
  <br>


<%= link_to "Join Event", new_invitation_path(:event_id => @chosen_event.id)%>

<%= link_to "Home", root_path %>

app/views/invitations/_form.html.erb
<%= form_with(model: invitation, class: "contents") do |form| %>
  <% if invitation.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(invitation.errors.count, "error") %> prohibited this invitation from being saved:</h2>

      <ul>
        <% invitation.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <%= form.hidden_field :attendee_id, value: current_user.id%>
  <%= form.hidden_field :event_id , value: params[:event_id]%>
  <div class="inline">
    <%= form.submit value: "Join" %>
  </div>
<% end %>

app/views/invitations/_invitation.html.erb
<div id="<%= dom_id invitation %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Event:</strong>
    <%= invitation.event_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Attendee:</strong>
    <%= invitation.attendee_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this invitation", invitation, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to 'Edit this invitation', edit_invitation_path(invitation), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/invitations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing invitation</h1>

  <%= render "form", invitation: @invitation %>

  <%= link_to "Show this invitation", @invitation, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to invitations", invitations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/invitations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Invitations</h1>
    <%= link_to 'New invitation', new_invitation_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="invitations" class="min-w-full">
    <%= render @invitations %>
  </div>
</div>

app/views/invitations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New invitation</h1>

  <%= render "form", invitation: @invitation, event: Event.find(params[:event_id]) %>

  <%= link_to 'Back to invitations', invitations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>
<br>

<%= link_to "back", root_path%>

app/views/invitations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @invitation %>

    <%= link_to 'Edit this invitation', edit_invitation_path(@invitation), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to 'Destroy this invitation', invitation_path(@invitation), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to 'Back to invitations', invitations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
 <p class="notice flex flex-row bg-cyan-500 text-white items-center justify-center w-screen h-6vh"><%= notice %></p>
 <p class="alert"><%= alert %></p>

app/views/users/show.html.erb
<%= @user.name %>

<% @organized_events.each do |event|%>
  <%= event.title %>
  <%= event.location %>
<% end %>

<p>upcoming events</p><br>
<% @future_events.each do |event|%>
  
  <%= event.title if event.attendees.find_by(id: current_user.id)%><br>
  
<% end %>
  <br>
<p>past events</p><br>
<% @past_events.each do |event|%>
  
   <%= event.title if event.attendees.find_by(id: current_user.id)%><br>

<% end %>


<%= link_to "Home", root_path %>